export const SKILLS_DATA = [
  "Welding", "Carpentry", "Masonry", "Plumbing", "Electrical Wiring", "Roofing", "Painting", "Drywall Installation", "Concrete Finishing", "Landscaping",
  "Forklift Operation", "Machine Operation", "Assembly Line", "Packaging", "Quality Control", "Inventory Management", "CNC Machining", "Soldering",
  "Data Entry", "Bookkeeping", "Customer Service", "Telecalling", "Reception", "Cashiering", "Delivery Driving", "Heavy Truck Driving", "Crane Operation",
  "Food Preparation", "Baking", "Cleaning", "Housekeeping", "Security Guarding", "Event Management", "Tailoring", "Sewing", "Pattern Making",
  // Let's add more up to 250
  "AC Repair", "Appliance Repair", "Automotive Repair", "Bicycle Repair", "Blacksmithing", "Bricklaying", "Cabinet Making", "Carpet Cleaning", "Catering", "Childcare",
  "Data Analysis", "Digital Marketing", "Drafting", "Elevator Installation", "Excavation", "Farming", "Fencing", "Floor Installation", "Furniture Assembly", "Gardening",
  "Glazing", "HVAC Installation", "Instrumentation", "Insulation", "Ironworking", "Janitorial Services", "Jewelry Making", "Knitting", "Laundry Services", "Leatherworking",
  "Locksmithing", "Logistics", "Machining", "Maintenance", "Meat Cutting", "Metalworking", "Milling", "Molding", "Moving Services", "Painting (Automotive)",
  "Pest Control", "Photography", "Pipefitting", "Plastering", "Printing", "Property Management", "Rigging", "Roofing", "Scaffolding", "Sheet Metal Work",
  "Sign Making", "Silversmithing", "Snow Removal", "Solar Installation", "Sound Engineering", "Stonecutting", "Street Sweeping", "Surveying", "Tiling", "Towing",
  "Tree Trimming", "Upholstery", "Waste Management", "Water Treatment", "Welding (TIG)", "Welding (MIG)", "Window Cleaning", "Woodworking", "3D Printing", "Accounting",
  "Administrative Assistance", "Advertising", "Agile Methodology", "Agronomy", "Animation", "App Development", "Architecture", "Artificial Intelligence", "Audio Editing", "AutoCAD",
  "Backend Development", "Bartending", "Big Data", "Biology", "Blockchain", "Blogging", "Brand Management", "Business Analysis", "C++ Programming", "Call Center Operations",
  "Catering Management", "Chemical Engineering", "Civil Engineering", "Cloud Computing", "Coaching", "Coding", "Communications", "Community Management", "Computer Networking", "Conflict Resolution",
  "Content Creation", "Copywriting", "Corporate Finance", "Counseling", "Creative Writing", "Crisis Management", "Cryptocurrency", "Cybersecurity", "Data Mining", "Data Science",
  "Database Administration", "Design Thinking", "Direct Sales", "E-commerce", "E-learning", "Economics", "Editing", "Electrical Engineering", "Email Marketing", "Engineering Management",
  "Entrepreneurship", "Environmental Science", "Event Planning", "Executive Coaching", "Facility Management", "Fashion Design", "Film Production", "Financial Analysis", "Financial Modeling", "First Aid",
  "Fitness Training", "Food Science", "Foreign Languages", "Fraud Detection", "Frontend Development", "Full Stack Development", "Fundraising", "Game Design", "Game Development", "Genetics",
  "Geology", "Graphic Design", "Growth Hacking", "Hardware Design", "Health & Safety", "Healthcare Administration", "Hospitality Management", "Human Resources", "Illustration", "Industrial Design",
  "Industrial Engineering", "Information Security", "Inside Sales", "Instructional Design", "Insurance", "Interaction Design", "Interior Design", "International Relations", "Investment Banking", "iOS Development",
  "ITIL", "Java Programming", "Journalism", "Law", "Leadership", "Lean Manufacturing", "Legal Research", "Library Science", "Logistics Management", "Machine Learning",
  "Management Consulting", "Manufacturing Engineering", "Market Research", "Marketing Strategy", "Materials Science", "Mathematics", "Mechanical Engineering", "Media Relations", "Medical Billing", "Medical Coding",
  "Merchandising", "Microbiology", "Mobile App Design", "Mobile Development", "Music Production", "Negotiation", "Network Security", "Neuroscience", "Nursing", "Nutrition",
  "Occupational Therapy", "Operations Management", "Optical Engineering", "Organizational Development", "Outside Sales", "Packaging Design", "Paralegal Skills", "Patient Care", "Payroll Administration", "Pharmacology",
  "Pharmacy", "Physical Therapy", "Physics", "Political Science", "Portfolio Management", "PR Strategy", "Pricing Strategy", "Print Design", "Process Engineering", "Process Improvement",
  "Product Marketing", "Product Management", "Production Planning", "Program Management", "Project Management", "Psychology", "Public Policy", "Public Relations", "Public Speaking", "Purchasing",
  "Python Programming", "Quality Assurance", "Quality Management", "Quantitative Analysis", "Radiology", "Real Estate", "Recruiting", "Renewable Energy", "Research", "Retail Management",
  "Risk Management", "Robotics", "Sales Management", "Sales Operations", "Salesforce", "Scheduling", "Scrum", "Search Engine Optimization (SEO)", "Social Media Marketing", "Software Architecture",
  "Software Engineering", "SolidWorks", "Solution Architecture", "Sorting", "Sourcing", "Special Education", "Speech Therapy", "Sports Management", "SQL", "Statistics",
  "Strategic Planning", "Supply Chain Management", "System Administration", "Systems Engineering", "Talent Management", "Tax Preparation", "Technical Support", "Technical Writing", "Telecommunications", "Testing",
  "Training", "Translation", "Troubleshooting", "Tutoring", "Typography", "UI/UX Design", "Underwriting", "User Experience (UX)", "User Interface Design (UI)", "User Research",
  "Venture Capital", "Veterinary Medicine", "Video Editing", "Video Production", "Virtualization", "Visual Merchandising", "Voice Acting", "Wealth Management", "Web Analytics", "Web Content",
  "Web Design", "Web Development", "Welding", "Wholesale", "Windows Administration", "Wireframing", "Wordpress", "Writing", "Yield Management", "Zoology"
];
